"""
generate_matlab.py — emit a MATLAB config function from the computed parameters.

Writes `config_parameters_mp.m`: a function returning the corrected effective
parameters for young/mature/aged, so the MATLAB validation suite can consume the
exact same numbers as the Python pipeline (single source of truth).
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Dict

from config import OUTPUT_DIR_MATLAB


def generate_matlab_config(params_list: List[Dict],
                           out_dir: Path = OUTPUT_DIR_MATLAB) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "config_parameters_mp.m"

    lines = []
    a = lines.append
    a("function P = config_parameters_mp(name)")
    a("%CONFIG_PARAMETERS_MP  Auto-generated effective SEI parameters.")
    a("%   Generated by programmes/src/generate_matlab.py from the verified")
    a("%   physics (Skills/sei_physics.py). Corrected conventions: dimensionless")
    a("%   base eta=eps/L; volumetric g_v (Option B). DO NOT EDIT BY HAND.")
    a("%")
    a("%   Usage:  P = config_parameters_mp('mature');")
    a("switch lower(name)")
    for p in params_list:
        a(f"    case '{p['composition_name']}'")
        a(f"        P.regime_name = '{p['composition_name']}';")
        a(f"        P.eps      = {p['eps_m']:.6e};   % SEI thickness [m]")
        a(f"        P.L        = {p['L_m']:.6e};")
        a(f"        P.alpha    = {p['alpha']:.6g};")
        a(f"        P.gamma    = {p['gamma']:.6g};")
        a(f"        P.delta    = {p['delta']:.6g};")
        a(f"        P.E_sei    = {p['E_sei_Pa']:.6e};   % [Pa]")
        a(f"        P.nu_sei   = {p['nu_sei']:.6g};")
        a(f"        P.D_sei    = {p['D_sei_m2s']:.6e};")
        a(f"        P.beta_sei = {p['beta_sei_m3_per_mol']:.6e};")
        a(f"        P.K_n_eff  = {p['K_n_eff_Pa_per_m']:.6e};   % [Pa/m]")
        a(f"        P.K_t_eff  = {p['K_t_eff_Pa_per_m']:.6e};")
        a(f"        P.R_eff    = {p['R_eff_s_per_m']:.6e};   % [s/m]")
        a(f"        P.D_eff    = {p['D_eff_m2s']:.6e};")
        a(f"        P.beta_eff = {p['beta_eff_m3_per_mol']:.6e};")
        a(f"        P.Gc       = {p['Gc_J_per_m2']:.6e};   % [J/m^2]")
        a(f"        P.delta_c  = {p['delta_c_m']:.6e};   % [m]")
        a(f"        P.regime   = '{p['mechanical_regime']}';")
    a("    otherwise")
    a("        error('config_parameters_mp:unknownName', ...")
    a("              'Unknown composition: %s (use young/mature/aged).', name);")
    a("end")
    a("end")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
